Received: from mail.demon.co.uk [91.221.168.68]
	by localhost with POP3 (fetchmail-5.9.0)
	for root@localhost (single-drop); Fri, 22 Feb 2013 11:34:41 +0000 (GMT)
Received: from smtp.demon.co.uk (91.221.168.43) by HVUT01.thus.corp
 (192.168.70.41) with Microsoft SMTP Server (TLS) id 14.1.355.2; Fri, 22 Feb
 2013 11:34:23 +0000
Received: from mdfmta002.net (unknown [127.0.0.1])	by
 mdfmta002.net (Postfix) with ESMTP id 988915F4060	for
 <administrator@greybox.demon.co.uk>; Fri, 22 Feb 2013 11:34:22 +0000 (GMT)
X-IronPort-AV: E=Sophos;i="4.84,715,1355097600"; 
   d="scan'208,217";a="10438046"
From: The Forwarder <recip1@senderdom.com>
To: "'yb@greybox.demon.co.uk'" <yb@greybox.demon.co.uk>
Date: Fri, 22 Feb 2013 11:33:46 +0000
Subject: Simple nested message
Thread-Topic: Simple nested message
Thread-Index: Ac4Q8Hmcxuwvw1SjQoa5nroZd57jpQ==
Message-ID: <BB4BnnnnnnnnnnnnnnnnBC91CAD52B402@aaaaaaabbccc.senderdom.com>
Accept-Language: en-US
Content-Language: en-US
X-MS-Has-Attach: yes
X-MS-TNEF-Correlator:
acceptlanguage: en-US
Content-Type: multipart/mixed;
	boundary="_004_F7F9BB4B2009684F950FE4ABBC91CAD52252B402DOM2MSGRCA02bar_"
X-MDF-HostID: 11
X-MDF-HostID: 11
Return-Path: recip1@senderdom.com
X-MS-Exchange-Organization-AuthSource: HVUT01.thus.corp
X-MS-Exchange-Organization-AuthAs: Anonymous
MIME-Version: 1.0

--_004_F7F9BB4B2009684F950FE4ABBC91CAD52252B402DOM2MSGRCA02bar_
Content-Type: multipart/alternative;
	boundary="_000_F7F9BB4B2009684F950FE4ABBC91CAD52252B402DOM2MSGRCA02bar_"

--_000_F7F9BB4B2009684F950FE4ABBC91CAD52252B402DOM2MSGRCA02bar_
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable

This message contains a simple nested message


________________________________
Footer blurb

--_000_F7F9BB4B2009684F950FE4ABBC91CAD52252B402DOM2MSGRCA02bar_
Content-Type: text/html; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable

<html xmlns:v=3D"urn:schemas-microsoft-com:vml" xmlns:o=3D"urn:schemas-micr=
osoft-com:office:office" xmlns:w=3D"urn:schemas-microsoft-com:office:word" =
xmlns:m=3D"http://schemas.microsoft.com/office/2004/12/omml" xmlns=3D"http:=
//www.w3.org/TR/REC-html40"><head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dus-ascii"=
>
<meta name=3D"Generator" content=3D"Microsoft Word 12 (filtered medium)">
<style>
<!--
 /* Font Definitions */
 @font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
 /* Style Definitions */
 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	margin-bottom:.0001pt;
	font-size:11.0pt;
	font-family:"Calibri","sans-serif";}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
a:visited, span.MsoHyperlinkFollowed
	{mso-style-priority:99;
	color:purple;
	text-decoration:underline;}
span.EmailStyle17
	{mso-style-type:personal-compose;
	font-family:"Calibri","sans-serif";
	color:windowtext;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page Section1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.Section1
	{page:Section1;}
-->
</style><!--[if gte mso 9]><xml>
 <o:shapedefaults v:ext=3D"edit" spidmax=3D"1026" />
</xml><![endif]--><!--[if gte mso 9]><xml>
 <o:shapelayout v:ext=3D"edit">
  <o:idmap v:ext=3D"edit" data=3D"1" />
 </o:shapelayout></xml><![endif]-->
</head>
<body lang=3D"EN-US" link=3D"blue" vlink=3D"purple">
<div class=3D"Section1">
<p class=3D"MsoNormal">This message contains a simple nested message<o:p></=
o:p></p>
<p class=3D"MsoNormal"><o:p>&nbsp;</o:p></p>
</div>
<br>
<hr>
<font face=3D"Arial" color=3D"Gray" size=3D"1">
Footer blurb
</font>
</body>
</html>

--_000_F7F9BB4B2009684F950FE4ABBC91CAD52252B402DOM2MSGRCA02bar_--

--_004_F7F9BB4B2009684F950FE4ABBC91CAD52252B402DOM2MSGRCA02bar_
Content-Type: message/rfc822

Received: from aaaaaaaaaaaa.senderdom.com ([::1]) by
 bbbbbbbbbbbbbb.senderdom.com ([::1]) with mapi; Wed, 20 Feb 2013 12:43:25
 +0000
From: senderA@sender1dom.com
To: Everybody <All@sender2dom.com>
Date: Wed, 20 Feb 2013 12:42:53 +0000
Subject: pd_admin
Thread-Topic: pxmin
Thread-Index: Ac4PbbbbbbbbbbqZQNUU4qQaoGCKQ==
Message-ID: <aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@bbbbbbbbbbbb.senderdom.com>
Accept-Language: en-US
Content-Language: en-US
X-MS-Exchange-Organization-AuthAs: Internal
X-MS-Exchange-Organization-AuthMechanism: 04
X-MS-Exchange-Organization-AuthSource: aaaaaaaaaaaaa1.senderdom.com
X-MS-Has-Attach:
X-Auto-Response-Suppress: DR, OOF, AutoReply
X-MS-Exchange-Organization-SCL: -1
X-MS-TNEF-Correlator:
acceptlanguage: en-US
Content-Type: multipart/alternative;
	boundary="_000_AC52BBE747F86D4BAF440B0D0295815B297B6D83DOM2MSGRCA02bar_"
MIME-Version: 1.0

--_000_AC52BBE747F86D4BAF440B0D0295815B297B6D83DOM2MSGRCA02bar_
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable

Inner message line 1.
Inner message line 2.
Inner message line 3.
Inner message line 4.





--_000_AC52BBE747F86D4BAF440B0D0295815B297B6D83DOM2MSGRCA02bar_
Content-Type: text/html; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable

<html xmlns:v=3D"urn:schemas-microsoft-com:vml" xmlns:o=3D"urn:schemas-micr=
osoft-com:office:office" xmlns:w=3D"urn:schemas-microsoft-com:office:word" =
xmlns:m=3D"http://schemas.microsoft.com/office/2004/12/omml" xmlns=3D"http:=
//www.w3.org/TR/REC-html40"><head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dus-ascii"=
>
<meta name=3D"Generator" content=3D"Microsoft Word 14 (filtered medium)">
<style><!--
/* Font Definitions */
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	margin-bottom:.0001pt;
	font-size:11.0pt;
	font-family:"Calibri","sans-serif";
	mso-fareast-language:EN-US;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
a:visited, span.MsoHyperlinkFollowed
	{mso-style-priority:99;
	color:purple;
	text-decoration:underline;}
span.EmailStyle17
	{mso-style-type:personal-compose;
	font-family:"Calibri","sans-serif";
	color:windowtext;}
.MsoChpDefault
	{mso-style-type:export-only;
	font-family:"Calibri","sans-serif";
	mso-fareast-language:EN-US;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:70.85pt 70.85pt 2.0cm 70.85pt;}
div.WordSection1
	{page:WordSection1;}
--></style><!--[if gte mso 9]><xml>
<o:shapedefaults v:ext=3D"edit" spidmax=3D"1026" />
</xml><![endif]--><!--[if gte mso 9]><xml>
<o:shapelayout v:ext=3D"edit">
<o:idmap v:ext=3D"edit" data=3D"1" />
</o:shapelayout></xml><![endif]-->
</head>
<body lang=3D"EN-GB" link=3D"blue" vlink=3D"purple">
<div class=3D"WordSection1">
Inner message line 1.<br/>
Inner message line 2.<br/>
Inner message line 3.<br/>
Inner message line 4.<br/>
<p></p>
<p class=3D"MsoNormal"><o:p>&nbsp;</o:p></p>
<p class=3D"MsoNormal"><o:p>&nbsp;</o:p></p>
<p class=3D"MsoNormal"><o:p>&nbsp;</o:p></p>
</div>
</body>
</html>

--_000_AC52BBE747F86D4BAF440B0D0295815B297B6D83DOM2MSGRCA02bar_--

--_004_F7F9BB4B2009684F950FE4ABBC91CAD52252B402DOM2MSGRCA02bar_--
